/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package licenceproject;

import java.util.TimerTask;
import javax.swing.Timer;
/**
 *
 * @author allessi
 */
public class DemanderAuthentification extends javax.swing.JFrame {
      boolean movement = true;
    /**
     * Creates new form DemanderAuthentification
     */
    public DemanderAuthentification() {
        initComponents();
        
    
    }
     
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bvn = new javax.swing.JLabel();
        bvm = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpen(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bvn.setFont(new java.awt.Font("LM Roman Demi 10", 2, 36)); // NOI18N
        bvn.setForeground(new java.awt.Color(0, 51, 51));
        bvn.setText("Bienvenu(e) sur votre application de réservation d'hôtel");
        getContentPane().add(bvn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 970, -1));

        bvm.setFont(new java.awt.Font("LM Roman Demi 10", 2, 24)); // NOI18N
        bvm.setForeground(new java.awt.Color(255, 255, 255));
        bvm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bvm.setText("Rendre plus rapide , plus efficace et plus simple vos réservations sont nos priorités");
        getContentPane().add(bvm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 60));

        jButton1.setBackground(new java.awt.Color(0, 0, 0,50));
        jButton1.setFont(new java.awt.Font("LM Roman Demi 10", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DEMANDER AUTHENTIFICATION");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 570, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/licenceproject/Images/CC.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1360, 705));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Authentification Auth =new Authentification();
         Auth.setVisible(true);
        this.setVisible(false);
        
                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void WindowOpen(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpen
       
        
        final int MAX_X = 450;
        final int MIN_X = 50;
        
        Thread animation = new Thread (new Runnable(){
           // @override
            public void run(){
                int x= 20;
                int y= 30;
                boolean checked=true;
                while(true){
                    if(checked){
             
                   bvn.setLocation(x, y);
                    x +=10;
                    }else{
                        bvn.setLocation(x, y);
                    x -=10;
                    }
                    if(x>MAX_X){
                        checked=false;
                        x=400; //reset the x value
                    }
                    if(x<MIN_X){
                        checked= true;
                    }
                    try{
                        Thread.sleep(200);
                    }catch(Exception e){
                        
                    }
                }
            }
        });
        animation.start();
    }//GEN-LAST:event_WindowOpen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemanderAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemanderAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemanderAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemanderAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemanderAuthentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bvm;
    private javax.swing.JLabel bvn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
